name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Lint Python code
        run: bunx ruff check update_results.py tests

      - name: Check Python code formatting
        run: bunx ruff format --check update_results.py tests

      - name: Run tests
        run: python -m unittest discover
